name: Commit checker

on:
  pull_request:

jobs:
  commit-checker:
    name: Commit checker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 4

    - name: Get pull-request commits
      uses: openttd/actions/checkout-pull-request@v2

    - name: Checkout commit-checker
      uses: OpenTTD/OpenTTD-git-hooks@main
