name: Deployment

on:
  deployment:

jobs:
  deploy_to_aws:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
    - name: Deployment in progress
      uses: openttd/actions/deployments-update@v2
      with:
        github-token: ${{ secrets.DEPLOYMENT_TOKEN }}
        state: in_progress
        description: "Deployment of ${{ github.event.deployment.payload.version }} to ${{ github.event.deployment.environment }} started"

    - name: Deploy on AWS
      uses: openttd/actions/deploy-aws@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: ${{ secrets.AWS_REGION }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        name: Wiki

    - if: success()
      name: Deployment successful
      uses: openttd/actions/deployments-update@v2
      with:
        github-token: ${{ secrets.DEPLOYMENT_TOKEN }}
        state: success
        description: "Successfully deployed ${{ github.event.deployment.payload.version }} on ${{ github.event.deployment.environment }}"

    - if: failure() || cancelled()
      name: Deployment failed
      uses: openttd/actions/deployments-update@v2
      with:
        github-token: ${{ secrets.DEPLOYMENT_TOKEN }}
        state: failure
