name: End-to-end Testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  playwright:
    name: Playwright
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Set up packages
      run: |
        python -m pip install --upgrade pip
        pip install -r e2e/requirements.base
        pip install -r requirements.txt
        playwright install
    - name: Playwright
      run: |
        COVERAGE_FILE="$(pwd)/.coverage" pytest e2e
    - name: Coverage report
      run: |
        coverage report -m
        coverage html
        coverage xml
    - name: Archive coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
