name: Publish image

on:
  push:
    branches:
    - master
    tags:
    - '*'
  repository_dispatch:
    types:
    - publish_latest_tag
    - publish_master

jobs:
  publish_image:
    name: Publish image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - if: github.event_name == 'repository_dispatch'
      name: Repository dispatch
      uses: openttd/actions/checkout-dispatch@v2

    - name: Checkout tags and submodules
      uses: openttd/actions/checkout@v2
      with:
        with-tags: true

    - name: Set variables
      id: vars
      uses: openttd/actions/docker-vars@v2
      with:
        registry-username: ${{ secrets.GHCR_USERNAME }}

    - name: Build
      uses: openttd/actions/docker-build@v2
      with:
        name: ${{ steps.vars.outputs.name }}
        tag: ${{ steps.vars.outputs.tag }}
        tags: ${{ steps.vars.outputs.tags }}
        version: ${{ steps.vars.outputs.version }}
        date: ${{ steps.vars.outputs.date }}
        registry: ghcr.io

    - if: steps.vars.outputs.dry-run == 'false'
      name: Publish
      id: publish
      uses: openttd/actions/docker-publish@v2
      with:
        registry-username: ${{ secrets.GHCR_USERNAME }}
        registry-password: ${{ secrets.GHCR_PASSWORD }}
        registry: ghcr.io
        name: ${{ steps.vars.outputs.name }}
        tag: ${{ steps.vars.outputs.tag }}

    - if: steps.vars.outputs.dry-run == 'false'
      name: Trigger deployment
      uses: openttd/actions/deployments-create@v2
      with:
        ref: ${{ steps.vars.outputs.sha }}
        environment: ${{ steps.vars.outputs.environment }}
        version: ${{ steps.vars.outputs.version }}
        date: ${{ steps.vars.outputs.date }}
        docker-tag: ${{ steps.publish.outputs.remote-tag }}
        github-token: ${{ secrets.DEPLOYMENT_TOKEN }}
