name: Release

on:
  push:
    branches:
    - main
  release:
    types:
    - published

jobs:
  release:
    name: Release
    uses: OpenTTD/actions/.github/workflows/rw-entry-release-docker-nomad.yml@v4
    secrets: inherit
    with:
      service: wiki-prod
      url: https://wiki.openttd.org/
